'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>www.unidaddigital01.com</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public ReadOnly Property DominioAborrar() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("DominioAborrar"),Global.System.Collections.Specialized.StringCollection)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.noip.com/api/mdns/api-rpc.php")>  _
        Public ReadOnly Property url_NoIP() As String
            Get
                Return CType(Me("url_NoIP"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("dns@publicar.com")>  _
        Public ReadOnly Property email_NoIP() As String
            Get
                Return CType(Me("email_NoIP"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("publicar_dns")>  _
        Public ReadOnly Property customerid_NoIP() As String
            Get
                Return CType(Me("customerid_NoIP"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("appBorrarDominio.log")>  _
        Public ReadOnly Property LogFileName() As String
            Get
                Return CType(Me("LogFileName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:/LogsAppPropias/BorradoDominiosNoip/")>  _
        Public ReadOnly Property StatsLogFilePath() As String
            Get
                Return CType(Me("StatsLogFilePath"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("107.23.132.196")>  _
        Public ReadOnly Property IPSitioWeb() As String
            Get
                Return CType(Me("IPSitioWeb"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("sitemail.everyone.net")>  _
        Public Property infoMXEveryOne1() As String
            Get
                Return CType(Me("infoMXEveryOne1"),String)
            End Get
            Set
                Me("infoMXEveryOne1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("sitemail2.everyone.net")>  _
        Public Property infoMXEveryOne2() As String
            Get
                Return CType(Me("infoMXEveryOne2"),String)
            End Get
            Set
                Me("infoMXEveryOne2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.2.3.4")>  _
        Public Property IPSitioWeb_Infoplus() As String
            Get
                Return CType(Me("IPSitioWeb_Infoplus"),String)
            End Get
            Set
                Me("IPSitioWeb_Infoplus") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("dominiosInfoPlus")>  _
        Public Property grupoInfoPlus_NoIP() As String
            Get
                Return CType(Me("grupoInfoPlus_NoIP"),String)
            End Get
            Set
                Me("grupoInfoPlus_NoIP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("dominiosPropios")>  _
        Public Property grupoDominios_NoIP() As String
            Get
                Return CType(Me("grupoDominios_NoIP"),String)
            End Get
            Set
                Me("grupoDominios_NoIP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("domPropiosAdminSites")>  _
        Public Property grupoAdminSites_NoIP() As String
            Get
                Return CType(Me("grupoAdminSites_NoIP"),String)
            End Get
            Set
                Me("grupoAdminSites_NoIP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("siteurl.everyone.net")>  _
        Public Property SitioInfoMXEveryOne() As String
            Get
                Return CType(Me("SitioInfoMXEveryOne"),String)
            End Get
            Set
                Me("SitioInfoMXEveryOne") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("pop.everyone.net")>  _
        Public Property infoPopEveryOne() As String
            Get
                Return CType(Me("infoPopEveryOne"),String)
            End Get
            Set
                Me("infoPopEveryOne") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("smtp.everyone.net")>  _
        Public Property infoSmtpEveryOne() As String
            Get
                Return CType(Me("infoSmtpEveryOne"),String)
            End Get
            Set
                Me("infoSmtpEveryOne") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("imap.everyone.net")>  _
        Public Property infoImapEveryOne() As String
            Get
                Return CType(Me("infoImapEveryOne"),String)
            End Get
            Set
                Me("infoImapEveryOne") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("quimera.frontier.com.br")>  _
        Public Property infoMXBrasil() As String
            Get
                Return CType(Me("infoMXBrasil"),String)
            End Get
            Set
                Me("infoMXBrasil") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("webmailpublicar.frontier.com.br")>  _
        Public Property infoWebmailBrasil() As String
            Get
                Return CType(Me("infoWebmailBrasil"),String)
            End Get
            Set
                Me("infoWebmailBrasil") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("quimera.frontier.com.br")>  _
        Public Property infoPopBrasil() As String
            Get
                Return CType(Me("infoPopBrasil"),String)
            End Get
            Set
                Me("infoPopBrasil") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("quimera.frontier.com.br")>  _
        Public Property infoSmtpBrasil() As String
            Get
                Return CType(Me("infoSmtpBrasil"),String)
            End Get
            Set
                Me("infoSmtpBrasil") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("107.23.132.196")>  _
        Public Property IPReadServer() As String
            Get
                Return CType(Me("IPReadServer"),String)
            End Get
            Set
                Me("IPReadServer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Administracion2013!.$")>  _
        Public Property Password() As String
            Get
                Return CType(Me("Password"),String)
            End Get
            Set
                Me("Password") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.AdminDominios.My.MySettings
            Get
                Return Global.AdminDominios.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
