//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5446
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=2.0.50727.5446.
// 
#pragma warning disable 1591

namespace WinClientWSKatarrValidity.WSKatarrValidity {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="KatarrValidityServiceSoap", Namespace="http://tempuri.org/")]
    public partial class KatarrValidityService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ActivateProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActivateItemOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public KatarrValidityService() {
            this.Url = global::WinClientWSKatarrValidity.Properties.Settings.Default.WinClientWSKatarrValidity_WSKatarrValidity_KatarrValidityService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ActivateProductCompletedEventHandler ActivateProductCompleted;
        
        /// <remarks/>
        public event ActivateItemCompletedEventHandler ActivateItemCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActivateProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ActivateProduct(string sCompanyId, string sProductId, int iSystemId) {
            object[] results = this.Invoke("ActivateProduct", new object[] {
                        sCompanyId,
                        sProductId,
                        iSystemId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ActivateProductAsync(string sCompanyId, string sProductId, int iSystemId) {
            this.ActivateProductAsync(sCompanyId, sProductId, iSystemId, null);
        }
        
        /// <remarks/>
        public void ActivateProductAsync(string sCompanyId, string sProductId, int iSystemId, object userState) {
            if ((this.ActivateProductOperationCompleted == null)) {
                this.ActivateProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActivateProductOperationCompleted);
            }
            this.InvokeAsync("ActivateProduct", new object[] {
                        sCompanyId,
                        sProductId,
                        iSystemId}, this.ActivateProductOperationCompleted, userState);
        }
        
        private void OnActivateProductOperationCompleted(object arg) {
            if ((this.ActivateProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActivateProductCompleted(this, new ActivateProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActivateItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ActivateItem(string sContractId, string sReferenceId, int iMovenment, int iSystemId) {
            this.Invoke("ActivateItem", new object[] {
                        sContractId,
                        sReferenceId,
                        iMovenment,
                        iSystemId});
        }
        
        /// <remarks/>
        public void ActivateItemAsync(string sContractId, string sReferenceId, int iMovenment, int iSystemId) {
            this.ActivateItemAsync(sContractId, sReferenceId, iMovenment, iSystemId, null);
        }
        
        /// <remarks/>
        public void ActivateItemAsync(string sContractId, string sReferenceId, int iMovenment, int iSystemId, object userState) {
            if ((this.ActivateItemOperationCompleted == null)) {
                this.ActivateItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActivateItemOperationCompleted);
            }
            this.InvokeAsync("ActivateItem", new object[] {
                        sContractId,
                        sReferenceId,
                        iMovenment,
                        iSystemId}, this.ActivateItemOperationCompleted, userState);
        }
        
        private void OnActivateItemOperationCompleted(object arg) {
            if ((this.ActivateItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActivateItemCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void ActivateProductCompletedEventHandler(object sender, ActivateProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActivateProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActivateProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void ActivateItemCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591